name: ml_functional
channels:
  - defaults
  - conda-forge
dependencies:
  - pandas=2.1.4
  - pip=23.3.1
  - drfp==0.3.6
  - hyperopt==0.2.7
  - rdkit==2023.9.2
  - scikit-learn==1.3.2
  - xyz2mol==0.1.2
  - pip:
      - xgboost==2.0.2
